
Write-Host " My voice is my passport, verify me "
Write-Host "  LOL U LOSE"
Write-Host " My voice is my passport, verify me "
Write-Host "   LOL U LOSE"
Write-Host " My voice is my passport, verify me "
Write-Host "    LOL U LOSE"
Write-Host " My voice is my passport, verify me "
Write-Host "     LOL U LOSE"
Write-Host " My voice is my passport, verify me "
Write-Host "      LOL U LOSE"
Write-Host " My voice is my passport, verify me "
Write-Host "       LOL U LOSE"
Write-Host " My voice is my passport, verify me "
Write-Host "        LOL U LOSE"
